server:
  port: 8088
#  servlet:
#    context-path: /
#    encoding:
#      charset: UTF-8
#      enabled: true

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/media_project
    username: root
    password: kien1997
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

#  mvc:
#    view:
#      prefix: /WEB-INF/pages
#      suffix: .jsp
#
#  thymeleaf:
#    cache: true
#    check-template-location: true
#    servlet:
#      content-type: text/html
#    enabled: true
#    encoding: UTF-8
#    excluded-view-names:
#    mode: HTML5
#    prefix: classpath:/templates
#    suffix: html
#
#logging:
#  level:
#    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
