server:
  port: 8088

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/media-project
    username: root
    password: kien1997
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
